countries = [
  {code: "FR", count: 336836},
  {code: "PL", count: 331608},
  #{code: "", count: 129668}, # needs a change in rule
  {code: "DE", count: 154396},
  {code: "UK", count: 102841},
  #{code: "no-country", count: 76458}, # needs a change in rule
  {code: "IT", count: 60081},
  {code: "RO", count: 52504},
  {code: "ES", count: 43433},
  {code: "CZ", count: 40049},
  {code: "BE", count: 35289},
  {code: "BG", count: 34950},
  {code: "LV", count: 29944},
  {code: "SE", count: 28319},
  {code: "LT", count: 28027},
  {code: "NL", count: 26860},
  {code: "HU", count: 23363},
  {code: "SI", count: 21398},
  {code: "DK", count: 20507},
  {code: "NO", count: 18494},
  {code: "FI", count: 17178},
  {code: "GR", count: 16840},
  {code: "SK", count: 16587},
  {code: "AT", count: 16198},
  {code: "CH", count: 8766},
  {code: "EE", count: 8400},
  {code: "PT", count: 8318},
  {code: "IE", count: 7951},
  {code: "LU", count: 3298},
  {code: "CY", count: 3107},
  {code: "HR", count: 2119},
  {code: "MT", count: 1145},
  {code: "US", count: 625},
  {code: "MK", count: 620},
  {code: "GP", count: 582},
  {code: "IS", count: 503},
  {code: "RE", count: 481},
  {code: "AW", count: 267},
  {code: "MQ", count: 255},
  {code: "IN", count: 123},
  {code: "CA", count: 113},
  {code: "AF", count: 102},
  {code: "GF", count: 61},
  {code: "RU", count: 56},
  {code: "CD", count: 55},
  {code: "CN", count: 45},
  {code: "KE", count: 45},
  {code: "UA", count: 41},
  {code: "JP", count: 37},
  {code: "RS", count: 36},
  {code: "TW", count: 36},
  {code: "LI", count: 33},
  {code: "TR", count: 33},
  {code: "SM", count: 33},
  {code: "SD", count: 31},
  {code: "GI", count: 31},
  {code: "ZA", count: 29},
  {code: "KR", count: 26},
  {code: "IL", count: 24},
  {code: "AE", count: 21},
  {code: "AU", count: 20},
  {code: "BI", count: 17},
  {code: "UM", count: 17},
  {code: "BA", count: 16},
  {code: "AL", count: 16},
  {code: "MU", count: 16},
  {code: "BF", count: 16},
  {code: "YT", count: 15},
  {code: "TZ", count: 14},
  {code: "BY", count: 13},
  {code: "MD", count: 13},
  {code: "BJ", count: 13},
  {code: "GE", count: 13},
  {code: "BD", count: 13},
  {code: "UG", count: 11},
  {code: "ME", count: 11},
  {code: "HK", count: 10},
  {code: "MZ", count: 10},
  {code: "ML", count: 10},
  {code: "MC", count: 10},
  {code: "SG", count: 10},
  {code: "UY", count: 10},
  {code: "BR", count: 9},
  {code: "RW", count: 9},
  {code: "DO", count: 9},
  {code: "MW", count: 9},
  {code: "AN", count: 8},
  {code: "PK", count: 8},
  {code: "TN", count: 8},
  {code: "SR", count: 7},
  {code: "ZM", count: 7},
  {code: "LS", count: 7},
  {code: "ZW", count: 7},
  {code: "1A", count: 7},
  {code: "BO", count: 7},
  {code: "ET", count: 7},
  {code: "TC", count: 6},
  {code: "TD", count: 6},
  {code: "MR", count: 6},
  {code: "GH", count: 6},
  {code: "DZ", count: 6},
  {code: "CI", count: 6},
  {code: "DJ", count: 5},
  {code: "LK", count: 5},
  {code: "JO", count: 5},
  {code: "FK", count: 5},
  {code: "AZ", count: 5},
  {code: "PS", count: 5},
  {code: "UZ", count: 4},
  {code: "SN", count: 4},
  {code: "CF", count: 4},
  {code: "BW", count: 4},
  {code: "NE", count: 4},
  {code: "VE", count: 4},
  {code: "PE", count: 4},
  {code: "NA", count: 4},
  {code: "TJ", count: 4},
  {code: "MA", count: 4},
  {code: "KZ", count: 4},
  {code: "GA", count: 4},
  {code: "NI", count: 4},
  {code: "SA", count: 4},
  {code: "NC", count: 4},
  {code: "PA", count: 4},
  {code: "LB", count: 4},
  {code: "NG", count: 4},
  {code: "EG", count: 4},
  {code: "SO", count: 4},
  {code: "AM", count: 3},
  {code: "NZ", count: 3},
  {code: "JE", count: 3},
  {code: "CO", count: 3},
  {code: "AR", count: 3},
  {code: "GN", count: 3},
  {code: "PH", count: 3},
  {code: "LA", count: 3},
  {code: "CR", count: 3},
  {code: "SZ", count: 3},
  {code: "IR", count: 3},
  {code: "ID", count: 3},
  {code: "SV", count: 3},
  {code: "AO", count: 2},
  {code: "IM", count: 2},
  {code: "KH", count: 2},
  {code: "MY", count: 2},
  {code: "JM", count: 2},
  {code: "VG", count: 2},
  {code: "MM", count: 2},
  {code: "AD", count: 2},
  {code: "FO", count: 2},
  {code: "GW", count: 2},
  {code: "AI", count: 2},
  {code: "GT", count: 2},
  {code: "VU", count: 2},
  {code: "VI", count: 2},
  {code: "PF", count: 2},
  {code: "TT", count: 2},
  {code: "BB", count: 2},
  {code: "HN", count: 2},
  {code: "KP", count: 2},
  {code: "VN", count: 2},
  {code: "GS", count: 2},
  {code: "KG", count: 1},
  {code: "KN", count: 1},
  {code: "SH", count: 1},
  {code: "CL", count: 1},
  {code: "TV", count: 1},
  {code: "MX", count: 1},
  {code: "OM", count: 1},
  {code: "SL", count: 1},
  {code: "GM", count: 1},
  {code: "FM", count: 1},
  {code: "PY", count: 1},
  {code: "TK", count: 1},
  {code: "GL", count: 1},
  {code: "FJ", count: 1},
  {code: "CX", count: 1},
  {code: "IQ", count: 1},
  {code: "IO", count: 1},
  {code: "VA", count: 1},
  {code: "ER", count: 1},
  {code: "LY", count: 1},
  {code: "CU", count: 1},
  {code: "PR", count: 1},
  {code: "MG", count: 1},
  {code: "CM", count: 1},
  {code: "LR", count: 1},
  {code: "NP", count: 1},
  {code: "SC", count: 1},
  {code: "SS", count: 1},
  {code: "GY", count: 1},
  {code: "AX", count: 1} 
].sort{|i| i.count}


puts "Start running"

countries.each do |country|
  if country[:count] >= 50_000
    puts "Skipping #{country[:code]}, it has #{country[:count]} BE instances"
    next
  end
  
  blocks = [country[:count] / 5, 1].max
  
  template = File.open("config.xml", "r")
  config = template.read
  template.close
  config = config.gsub(/XX/, country[:code]).gsub(/BB/, blocks.to_s)
  config_path = "config-#{country[:code]}.xml"
  file = File.open(config_path, "w")
  file.write config
  file.close
  
  puts "Wrote config for #{country[:code]}"
  start = Time.now
  puts %x{"C:\\Program Files\\Java\\jre7\\bin\\java.exe" -Xmx4g -DconfigFile=#{config_path} -jar "c:\\Program Files\\Silk Workbench\\commandline\\silk.jar\" 2> log-#{country[:code]}.log}
  endt = Time.now
  diff = endt - start
  puts "Finished #{country[:code]} with #{country[:count]} BE instances in #{diff} secs"
end